from polymer.agent import A1
# Initialize the agent with data path, Data lake will be automatically downloaded on first run (~11GB)
# agent = A1(path='/home/hcao5/workspace/datasets', llm='gpt-5.6-luna')
# claude-sonnet-5 claude-haiku-4-5-20251001 deepseek-v4-pro
agent = A1(path='/home/hcao5/workspace/datasets', llm='claude-haiku-4-5-20251001')

# agent.go("You are a polymer chemist planning the first lab campaign to make a linear, solution-processable polyester whose constitutional repeating unit is the condensation product of **terephthalic acid** and **1,4-butanediol** (PBT-type CRU). The target is not “make any PBT.” Constraints: - Use only commercially catalogued monomers (no custom multi-step monomer synthesis). - Number-average molar mass \(M_n = 15\)–\(25\,\mathrm{kDa}\), \(Đ \le 2.0\). - Residual carboxylic acid end-groups low enough that a later melt-compounding step at \(250^\circ\mathrm{C}\) does not cause visible bubbling. - The isolated polymer must dissolve at \(\ge 50\,\mathrm{mg\,mL^{-1}}\) in a common organic solvent at \(25^\circ\mathrm{C}\) for GPC and coating. - You have one week of hood time, a 100 mL flask or small melt reactor, no continuous vacuum-finishing line, and you must justify every extra experiment. A virtual screen of synthesizable CRUs flagged this chemistry as electronically attractive (stiff aromatic diester, polarizable repeat unit), but that screen says nothing about how to run the polymerization, how far conversion must go, or which process failure modes kill \(M_n\), \(Đ\), solubility, or thermal stability. Specify which formulation and process variables you would change on the first campaign, the levels or ranges you would actually run, what you would hold as controls, which characterization methods decide whether a run is a success or a dead end, and the rule you would use to choose which single modification to pursue next if the first design fails. Do not list a textbook polymerization in general terms. Give a concrete experimental matrix and a stop/go criterion.")

# tool

# agent.go("Plan a RAFT comonomer screen for solvent-free, PFAS-free hydrophobic coatings: generate 32 (meth)acrylate / styrene-type pairs that maximize predicted water contact angle and keep film $T_g$ in 40–80 °C so the coating is film-forming at 120 °C. Every monomer ≤3 steps from commercial (meth)acryloyl chloride or 4-vinylbenzyl chloride.")
# agent.go("From comme·rcially catalogued 5–7-membered lactones and cyclic anhydrides, propose 16 ROP/ROCOP comonomer pairs that (i) contain only C/H/O, (ii) have an ester or anhydride in both monomers, (iii) have RDKit-estimated oligomer $T_g$ descriptors above a fixed cutoff, and (iv) are each resolvable to a PubChem CID. Return a 16-row table: A_SMILES, B_SMILES, A_CID, B_CID, reaction (ROP or ROCOP).")

# datasets

# agent.go("List the 10 most common composition strings that contain C and H and at least one of O, N, S, F, Cl in Omol25. Report counts.")
# agent.go("For hydrogen-rich organic systems typical of polymer subchains, how does the HOMO–LUMO gap change as the fragment grows from small oligomers to ~100+ atom clusters? Is the drop mostly finished by a particular size, or does it keep falling")
# agent.go("The following is a polymer science question.Think step by step if needed, then give the exact short final answer.Question: The efficiency of photocatalytic [2+2] cycloaddition polymerization and the molecular weight of the resulting polymers are influenced by the monomer structure. Please refer to the experimental data in the table below and rank the following different diene monomers according to the weight-average molecular weight (Mw) of the polymers obtained after polymerization under specific conditions, from smallest to largest. a: Monomer 1c b: Monomer 1f c: Monomer 1a d: Monomer 1ePut the final answer inside <solution>...</solution>.For a number, output only the number (and unit if asked). For a ranking, output the ordered list. Do not put extra commentary inside the solution tags.")
agent.go("Starting from the existing data lake, consider one to three richly chemical polymer synthesis questions, you should read the content of datalake as auxillary, but not explicitly mention it to make chemical question general.")

